apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"mongodbapi-service","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"mongodbapi-pod"},"type":"ClusterIP"}}
  creationTimestamp: "2025-06-16T17:22:24Z"
  name: mongodbapi-service
  namespace: default
  resourceVersion: "11105"
  uid: cb9f08e7-7ee4-41b2-bb2c-cf6ce40bab02
spec:
  clusterIP: 10.97.128.213
  clusterIPs:
  - 10.97.128.213
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mongodbapi-pod
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
